DO $$ BEGIN
 CREATE TYPE "public"."USER_ROLES" AS ENUM('USER', 'ADMIN');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
ALTER TABLE "user" ADD COLUMN "USER_ROLES" "USER_ROLES" DEFAULT 'USER' NOT NULL;